apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  annotations:
    iam.gke.io/gcp-service-account: gke-cluster-sa@praktikum2-494215.iam.gserviceaccount.com
# gke-cluster-sa@praktikum2-494215.iam.gserviceaccount.com