//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetSpec) DeepCopyInto(out *DatasetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetSpec.
func (in *DatasetSpec) DeepCopy() *DatasetSpec {
	if in == nil {
		return nil
	}
	out := new(DatasetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedTraining) DeepCopyInto(out *DistributedTraining) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedTraining.
func (in *DistributedTraining) DeepCopy() *DistributedTraining {
	if in == nil {
		return nil
	}
	out := new(DistributedTraining)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DistributedTraining) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedTrainingHistory) DeepCopyInto(out *DistributedTrainingHistory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedTrainingHistory.
func (in *DistributedTrainingHistory) DeepCopy() *DistributedTrainingHistory {
	if in == nil {
		return nil
	}
	out := new(DistributedTrainingHistory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DistributedTrainingHistory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedTrainingHistoryList) DeepCopyInto(out *DistributedTrainingHistoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DistributedTrainingHistory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedTrainingHistoryList.
func (in *DistributedTrainingHistoryList) DeepCopy() *DistributedTrainingHistoryList {
	if in == nil {
		return nil
	}
	out := new(DistributedTrainingHistoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DistributedTrainingHistoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedTrainingHistorySpec) DeepCopyInto(out *DistributedTrainingHistorySpec) {
	*out = *in
	out.Throughput = in.Throughput.DeepCopy()
	out.TrainingSeconds = in.TrainingSeconds.DeepCopy()
	out.TotalWork = in.TotalWork.DeepCopy()
	out.ProvisioningSeconds = in.ProvisioningSeconds.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedTrainingHistorySpec.
func (in *DistributedTrainingHistorySpec) DeepCopy() *DistributedTrainingHistorySpec {
	if in == nil {
		return nil
	}
	out := new(DistributedTrainingHistorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedTrainingList) DeepCopyInto(out *DistributedTrainingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DistributedTraining, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedTrainingList.
func (in *DistributedTrainingList) DeepCopy() *DistributedTrainingList {
	if in == nil {
		return nil
	}
	out := new(DistributedTrainingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DistributedTrainingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedTrainingSpec) DeepCopyInto(out *DistributedTrainingSpec) {
	*out = *in
	if in.PytorchSpec != nil {
		in, out := &in.PytorchSpec, &out.PytorchSpec
		*out = new(PytorchSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SparkSpec != nil {
		in, out := &in.SparkSpec, &out.SparkSpec
		*out = new(SparkSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Model.DeepCopyInto(&out.Model)
	out.Dataset = in.Dataset
	out.Hardware = in.Hardware
	out.Topology = in.Topology
	in.Optimization.DeepCopyInto(&out.Optimization)
	in.Training.DeepCopyInto(&out.Training)
	if in.Objective != nil {
		in, out := &in.Objective, &out.Objective
		*out = new(ObjectiveSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedTrainingSpec.
func (in *DistributedTrainingSpec) DeepCopy() *DistributedTrainingSpec {
	if in == nil {
		return nil
	}
	out := new(DistributedTrainingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedTrainingStatus) DeepCopyInto(out *DistributedTrainingStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.ProvisioningStartTime != nil {
		in, out := &in.ProvisioningStartTime, &out.ProvisioningStartTime
		*out = (*in).DeepCopy()
	}
	if in.TrainingStartTime != nil {
		in, out := &in.TrainingStartTime, &out.TrainingStartTime
		*out = (*in).DeepCopy()
	}
	if in.FinishTime != nil {
		in, out := &in.FinishTime, &out.FinishTime
		*out = (*in).DeepCopy()
	}
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = new(JobResults)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ResolvedTopology = in.ResolvedTopology
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedTrainingStatus.
func (in *DistributedTrainingStatus) DeepCopy() *DistributedTrainingStatus {
	if in == nil {
		return nil
	}
	out := new(DistributedTrainingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardwareSpec) DeepCopyInto(out *HardwareSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardwareSpec.
func (in *HardwareSpec) DeepCopy() *HardwareSpec {
	if in == nil {
		return nil
	}
	out := new(HardwareSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobResults) DeepCopyInto(out *JobResults) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobResults.
func (in *JobResults) DeepCopy() *JobResults {
	if in == nil {
		return nil
	}
	out := new(JobResults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoRASpec) DeepCopyInto(out *LoRASpec) {
	*out = *in
	if in.TargetModules != nil {
		in, out := &in.TargetModules, &out.TargetModules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoRASpec.
func (in *LoRASpec) DeepCopy() *LoRASpec {
	if in == nil {
		return nil
	}
	out := new(LoRASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSpec) DeepCopyInto(out *ModelSpec) {
	*out = *in
	if in.HFTokenSecret != nil {
		in, out := &in.HFTokenSecret, &out.HFTokenSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSpec.
func (in *ModelSpec) DeepCopy() *ModelSpec {
	if in == nil {
		return nil
	}
	out := new(ModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectiveSpec) DeepCopyInto(out *ObjectiveSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectiveSpec.
func (in *ObjectiveSpec) DeepCopy() *ObjectiveSpec {
	if in == nil {
		return nil
	}
	out := new(ObjectiveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimizationSpec) DeepCopyInto(out *OptimizationSpec) {
	*out = *in
	in.LoRA.DeepCopyInto(&out.LoRA)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimizationSpec.
func (in *OptimizationSpec) DeepCopy() *OptimizationSpec {
	if in == nil {
		return nil
	}
	out := new(OptimizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PytorchSpec) DeepCopyInto(out *PytorchSpec) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PytorchSpec.
func (in *PytorchSpec) DeepCopy() *PytorchSpec {
	if in == nil {
		return nil
	}
	out := new(PytorchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedTopology) DeepCopyInto(out *ResolvedTopology) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedTopology.
func (in *ResolvedTopology) DeepCopy() *ResolvedTopology {
	if in == nil {
		return nil
	}
	out := new(ResolvedTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SparkSpec) DeepCopyInto(out *SparkSpec) {
	*out = *in
	if in.Arguments != nil {
		in, out := &in.Arguments, &out.Arguments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SparkSpec.
func (in *SparkSpec) DeepCopy() *SparkSpec {
	if in == nil {
		return nil
	}
	out := new(SparkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologySpec) DeepCopyInto(out *TopologySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologySpec.
func (in *TopologySpec) DeepCopy() *TopologySpec {
	if in == nil {
		return nil
	}
	out := new(TopologySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrainingSpec) DeepCopyInto(out *TrainingSpec) {
	*out = *in
	if in.DDPFindUnusedParameters != nil {
		in, out := &in.DDPFindUnusedParameters, &out.DDPFindUnusedParameters
		*out = new(bool)
		**out = **in
	}
	if in.UseFastTokenizer != nil {
		in, out := &in.UseFastTokenizer, &out.UseFastTokenizer
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrainingSpec.
func (in *TrainingSpec) DeepCopy() *TrainingSpec {
	if in == nil {
		return nil
	}
	out := new(TrainingSpec)
	in.DeepCopyInto(out)
	return out
}
